### ISSUE TITLE
Uncaught error on wallet connect disconnect

### ISSUE THREAD

**Issue by 0xAlcibiades** [valorem-labs-inc/valorem-frontend#112]
<img width="1653" alt="Screen_Shot_2022-09-03_at_22 56 34" src="https://user-images.githubusercontent.com/89996683/188301042-69d80c7b-e2ee-455f-bfdb-aa0c802f08ba.png">

We need to catch this disconnect gracefully

**Comment by thal0x** [comment]
@0xAlcibiades I believe this has been resolved by #122
