### ISSUE TITLE
Add telemetry to in app button clicks

### ISSUE THREAD

**Issue by 0xAlcibiades** [valorem-labs-inc/valorem-frontend#120]
It would be nice to emit plausible events on button clicks so we can get anonymized user data and optimize flows.

Here is an example:

https://github.com/valorem-labs-inc/valorem-frontend/pull/119

**Comment by 0xAlcibiades** [comment]
https://plausible.io/docs/custom-event-goals - particularly, we'll want to log connected users wallet addresses to see who participated in the beta later.

**Comment by thal0x** [comment]
@0xAlcibiades are there any other particular events you're interested in? I've added one for tracking the wallet type on connect. Trying to think of things that can't already be derived from the Graph.
