### ISSUE TITLE
Options writing in the UI should align on fixed timestamps

### ISSUE THREAD

**Issue by 0xAlcibiades** [valorem-labs-inc/valorem-frontend#129]
Right now, every time a user writes, they need to create a new option type. The UI should align the timestamps at the next utc 00:01 rather than an offset from `now`.

**Comment by thal0x** [comment]
@0xAlcibiades does "next utc 00:01" mean align to the next minute? or are you saying beginning (for exercise) and end (for expiry) of the day?
