### ISSUE TITLE
Detect connected network from wallet and handle correctly

### ISSUE THREAD

**Issue by 0xAlcibiades** [valorem-labs-inc/valorem-frontend#18]
The user should be able to select which network to use

**Comment by thal0x** [comment]
Are the current options Mainnet and Rinkeby?

**Comment by 0xAlcibiades** [comment]
Yeah, I think that's it for now. I need to talk to the harmony folks to get a bounty for adding harmony support to web3 modal, at which point we'd likely add that. Assume we want to be able to provide a list of rpc details for n number of networks.

**Comment by thal0x** [comment]
> @thal0x what would it take to add a display of the connected network here, and then kick the user out to the connect wallet page whenever the network is not a supported one?

Honestly when I saw this issue my biggest roadblock was just where in the UI to put this. Other than that, not too hard.

**Comment by 0xAlcibiades** [comment]
I think, rather, that there should be a list of supported networks, the actual UI/UX of switching the network happens in the user wallet, and if they are on an unsupported network, we just kick them to the connect wallet page with the error bubble telling them which networks are supported.

**Comment by 0xAlcibiades** [comment]
As a user, I want the app to read the network I am connected to from my wallet provider and use that network automatically, or kick me to the connect wallet page if I am on an unsupported network and tell me the list of supported networks
