### ISSUE TITLE
holdings display needs pagination

### ISSUE THREAD

**Issue by 0xAlcibiades** [valorem-labs-inc/valorem-frontend#28]
Seems like, right now, only a subset are displaying.

**Comment by thal0x** [comment]
@0xAlcibiades do you want to paginate the vault, or just change the query to get all options and claims? 2nd option is definitely the easy path, adding pagination will take longer but better UX. Maybe post-MVP?

**Comment by 0xAlcibiades** [comment]
This should be easier to paginate with the merged view of long/short (options/claims) @thal0x

**Comment by 0xAlcibiades** [comment]
We did the UI part of this, but we need to paginate the query from the subgraph still.

**Comment by 0xAlcibiades** [comment]
This is complete now.
