### ISSUE TITLE
Production build loads blank white page

### ISSUE THREAD

**Issue by 0xAlcibiades** [valorem-labs-inc/valorem-frontend#35]
`npm run build` locally, or on the production deploy in heroku seems borked. Has been since @rglover hands over the code, whereas the dev build via `npm run dev` works.

**Comment by 0xAlcibiades** [comment]
![image](https://user-images.githubusercontent.com/89996683/174130244-6198bcdb-bb38-40c5-9ed9-aa0a7b3cf43e.png)

**Comment by thal0x** [comment]
Yeah but if you're running `next build` and `next run` it's still setting the `NODE_ENV` to `production` I believe. And there are parts of the code that depend on that.

**Comment by 0xAlcibiades** [comment]
This is resolved now, in #39
