### ISSUE TITLE
Invalid input dates should not be allowed on the custom options writing UI

### ISSUE THREAD

**Issue by 0xAlcibiades** [valorem-labs-inc/valorem-frontend#44]
![unknown](https://user-images.githubusercontent.com/89996683/174394255-965bfdc8-d8f7-489c-8f77-01e718e219f5.png)

Right now users can input invalid dates in the writing UI.

Users should only be able to choose today or later for the exercise timestamp, and at least 1 day after that for the expiry timestamp.

Additionally, those exercise and expiry timestamps should line up on the last UTC second of the day to reduce liquidity fragmentation.

**Comment by thal0x** [comment]
@0xAlcibiades "Additionally, those exercise and expiry timestamps should line up on the last UTC second of the day to reduce liquidity fragmentation.", should the exercise timestamp line up with the **first** UTC second of the day?

**Comment by 0xAlcibiades** [comment]
@thal0x Choose one of those and let's go with that.
