### ISSUE TITLE
Ability to view claim detail

### ISSUE THREAD

**Issue by 0xAlcibiades** [valorem-labs-inc/valorem-frontend#7]
Scenario: Felix has claim(s) ticket(s) and wants detail about them
Given Felix has connected a wallet and claim(s) in that wallet
When he clicks an claim from the vault
He should be able to view the details about that holding

**Comment by 0xAlcibiades** [comment]
Blocked by #2

**Comment by thal0x** [comment]
@0xAlcibiades what are the relevant pieces of data you want shown here?

**Comment by 0xAlcibiades** [comment]
struct Claim {
        uint256 option;
        uint112 amountWritten;
        uint112 amountExercised;
        bool claimed;
    }

The link to the option, and the underlying asset balances for the claim, as well as a placeholder button to redeem the claim. @thal0x

**Comment by 0xAlcibiades** [comment]
This is de facto done from a frontend perspective, though there is a fix needed to the data sources here: https://github.com/valorem-labs-inc/valorem-core/issues/50

**Comment by 0xAlcibiades** [comment]
@thal0x this regressed in #49 and needs to be rewired.
