### ISSUE TITLE
Add Discord CTAs to app

### ISSUE THREAD

**Issue by jonlpersson** [valorem-labs-inc/valorem-frontend#92]
Two components need to be built:

1. Toast component that slides into view from the bottom after a set time on page/in app (15 sec): [Figma screen](https://www.figma.com/file/ew96LdTN4UR7qqd3Tt50aH/Valorem-UI?node-id=1723%3A1352)

![image](https://user-images.githubusercontent.com/89996683/188236773-a08c85e6-d30c-4da5-8205-a0b945567593.png)

2. Pop-over modal that covers screen on exit intent: [Figma screen](https://www.figma.com/file/ew96LdTN4UR7qqd3Tt50aH/Valorem-UI?node-id=1723%3A1384)

![image](https://user-images.githubusercontent.com/89996683/188236894-036bded3-cffc-4a24-bf37-3b8779461a86.png)

I have left comments inside the Figma file explaining the intended behavior for both of them, but I will include it here as well:

## Toast component

Behavior: Slide in from bottom after ~15 seconds of being logged into the app. Show the very top of the element even when "closed" (see -> RightMessage behavior, e.g. on [edlatimore.com](https://edlatimore.com)).

## Pop-over modal

Behavior: Display on exit intent, and if possible disable trigger forever or for ~7 days once someone clicks "Join Discord." We don't want to bother people unnecessarily. Other than that, same intended behavior as other pop-over modals in the app (i.e. close by clicking the x-mark, hitting esc, or clicking outside the modal)

**Comment by 0xAlcibiades** [comment]
We added the toast CTA, remains to be seen if we want to add the exit popover

**Comment by 0xAlcibiades** [comment]
@thal0x let's also add the popover on exit intent.

**Comment by 0xAlcibiades** [comment]
We agreed to drop the popover for now, not to be too intrusive on the user.
